### ISSUE TITLE
Rate Limit exceeding - Diffent kinds of errors and no clear status code in exception

### ISSUE THREAD

**Issue by fntc** [fiskaly/fiskaly-sdk-dotnet#22]
I did a test generating 1000 documents (Start-Update-Finish) as data for an export and received two different kinds of HTTP 429.

One was returned by the API
`{"statusCode":429,"error":"Too Many Requests","message":"Rate limit exceeded, retry in 1 minute"}`
which keeps the FiskalyHttpError.Code empty.

and one that seems to come from some reverse proxy or loadbalancer that is a plain HTTP 429 (no json RPC):

&lt;html>
&lt;head>&lt;title>429 Too Many Requests&lt;/title>&lt;/head>
&lt;body>
&lt;center>&lt;h1>429 Too Many Requests&lt;/h1>&lt;/center>
&lt;hr>&lt;center>openresty&lt;/center>
&lt;/body>
&lt;/html>

and thus cannot be deserialized resulting in an **JsonReaderException** when trying to decode the base64 content in 

CreateFiskalyHttpError<T>(JsonRpcResponse<T> response){
...

FiskalyApiError errorBody = JsonConvert
                    .DeserializeObject<FiskalyApiError>(
                        Transformer.DecodeBase64Body(errorData.Response.Body));

...
}

- [ ] Catch JsonReaderException and return a proper FiskalyHttpError

- [ ] Add Error Code for rate limit to allow handling situation in code

- [ ] Proposal: Add Error Code enum for possible errors

**Comment by prempador** [comment]
Hello @fntc, 
Thanks for taking the time and creating this issue. 

As this was a very hot topic yesterday I will talk about this issue in detail here and link this comment from other issues. 

________

### General Answer and Statement

On Monday's deployment we added a rate limiter for the authentication endpoint, because we saw integrators sending a ton of requests against the authentication endpoint even after receiving a 401 error. As the authentication is shared across all of our APIs we are very cautious here, thus adding the limiter. 

- Yesterday after the first few people started testing again we saw that adding a request-limiter in a test-scenario resulted in integrators getting errors, most likely due to not optimal integration of our services, or bad implementation of their test-environment. 
- We also realized that the statusCode element returned by the rate-limiter was formatted differently than the status_code returned from our APIs, resulting in Exceptions from the fiskaly Client and the fiskaly-sdks.

As a result we disabled the rate-limiter for now, but we will add it back in as soon as we addressed the issues mentioned above. Most likely with a less strict number of maximum requests per minute. 

________

### Issue Specific Answer

Now to your specific scenario. Sending 1000 "Documents" at once, or directly following each other is not a realistic scenario. I know that you said that you just did it to create an export afterwards, but here the 429 Error is justifiable. 
This openresty error comes from the Load-Balancer and we are aware that it returns HTML at the moment and are working on a fix. 

We will look in a better handling of Exceptions and Errors that can occur, and we always welcome PRs if you want to take matters in you own hands.

Your proposal of an Error Code Enum is not realistic. Basically you should expect all errors mentioned in the API description, as well as errors that can be expected using a REST-API like: 400, 401, 429, 500, 501, ...


Best, 
@prempador

**Comment by prempador** [comment]
HTML Errors from the Backend will now be parsed to JSON Errors in the new v1.2.100. 

If you are still experiencing issues please reopen this issue.
